In [2]:

# EDA - Data Import and Export


# Import required libraries
import pandas as pd
import sqlite3

# Load the Hotel Booking dataset
df = pd.read_csv("/content/hotel_bookings.csv")

# Display the complete dataset
print("===== DATASET =====")
display(df)

# Display first five records
print("\n===== FIRST FIVE ROWS =====")
display(df.head())

# Display last five records
print("\n===== LAST FIVE ROWS =====")
display(df.tail())

# Display dataset information
print("\n===== DATASET INFORMATION =====")
df.info()

# Display statistical summary
print("\n===== STATISTICAL SUMMARY =====")
display(df.describe(include='all'))

# Display dataset shape
print("\nDataset Shape:")
print(df.shape)

# Display column names
print("\nColumns:")
print(df.columns)

# Check missing values
print("\n===== MISSING VALUES =====")
print(df.isnull().sum())

# Export dataset to CSV
df.to_csv("hotel_bookings_export.csv", index=False)
print("\nCSV file exported successfully!")

# Export dataset to Excel
df.to_excel("hotel_bookings_export.xlsx", index=False)
print("Excel file exported successfully!")

# Create SQLite database
conn = sqlite3.connect("hotel_booking.db")

# Export DataFrame to SQL table
df.to_sql(
    "hotel_bookings",
    conn,
    if_exists="replace",
    index=False
)

print("Dataset exported successfully to SQLite database!")

# Close the connection
conn.close()

===== DATASET =====

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27.0,1.0,0.0,0.0,2.0,...,No Deposit,NaN,NaN,0.0,Transient,0.0,0.0,0.0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27.0,1.0,0.0,0.0,2.0,...,No Deposit,NaN,NaN,0.0,Transient,0.0,0.0,0.0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27.0,1.0,0.0,1.0,1.0,...,No Deposit,NaN,NaN,0.0,Transient,75.0,0.0,0.0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27.0,1.0,0.0,1.0,1.0,...,No Deposit,304.0,NaN,0.0,Transient,75.0,0.0,0.0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27.0,1.0,0.0,2.0,2.0,...,No Deposit,240.0,NaN,0.0,Transient,98.0,0.0,1.0,Check-Out,2015-07-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7319,Resort Hotel,1,190,2016,August,32.0,2.0,2.0,5.0,3.0,...,No Deposit,240.0,NaN,0.0,Transient,250.0,0.0,0.0,Canceled,2016-03-10
7320,Resort Hotel,1,215,2016,August,32.0,2.0,2.0,5.0,2.0,...,No Deposit,240.0,NaN,0.0,Transient,240.0,0.0,0.0,Canceled,2016-07-26
7321,Resort Hotel,1,48,2016,August,32.0,2.0,2.0,9.0,2.0,...,No Deposit,240.0,NaN,0.0,Transient,189.0,0.0,0.0,Canceled,2016-06-19
7322,Resort Hotel,1,209,2016,August,32.0,2.0,4.0,10.0,2.0,...,No Deposit,240.0,NaN,0.0,Transient,158.0,0.0,0.0,Canceled,2016-01-08
7323,Resort Hotel,1,208,2016,Aug,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

===== FIRST FIVE ROWS =====

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27.0,1.0,0.0,0.0,2.0,...,No Deposit,NaN,NaN,0.0,Transient,0.0,0.0,0.0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27.0,1.0,0.0,0.0,2.0,...,No Deposit,NaN,NaN,0.0,Transient,0.0,0.0,0.0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27.0,1.0,0.0,1.0,1.0,...,No Deposit,NaN,NaN,0.0,Transient,75.0,0.0,0.0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27.0,1.0,0.0,1.0,1.0,...,No Deposit,304.0,NaN,0.0,Transient,75.0,0.0,0.0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27.0,1.0,0.0,2.0,2.0,...,No Deposit,240.0,NaN,0.0,Transient,98.0,0.0,1.0,Check-Out,2015-07-03

===== LAST FIVE ROWS =====

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
7319,Resort Hotel,1,190,2016,August,32.0,2.0,2.0,5.0,3.0,...,No Deposit,240.0,NaN,0.0,Transient,250.0,0.0,0.0,Canceled,2016-03-10
7320,Resort Hotel,1,215,2016,August,32.0,2.0,2.0,5.0,2.0,...,No Deposit,240.0,NaN,0.0,Transient,240.0,0.0,0.0,Canceled,2016-07-26
7321,Resort Hotel,1,48,2016,August,32.0,2.0,2.0,9.0,2.0,...,No Deposit,240.0,NaN,0.0,Transient,189.0,0.0,0.0,Canceled,2016-06-19
7322,Resort Hotel,1,209,2016,August,32.0,2.0,4.0,10.0,2.0,...,No Deposit,240.0,NaN,0.0,Transient,158.0,0.0,0.0,Canceled,2016-01-08
7323,Resort Hotel,1,208,2016,Aug,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

===== DATASET INFORMATION =====
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7324 entries, 0 to 7323
Data columns (total 32 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   hotel                           7324 non-null   object
 1   is_canceled                     7324 non-null   int64
 2   lead_time                       7324 non-null   int64
 3   arrival_date_year               7324 non-null   int64
 4   arrival_date_month              7324 non-null   object
 5   arrival_date_week_number        7323 non-null   float64
 6   arrival_date_day_of_month       7323 non-null   float64
 7   stays_in_weekend_nights         7323 non-null   float64
 8   stays_in_week_nights            7323 non-null   float64
 9   adults                          7323 non-null   float64
 10  children                        7323 non-null   float64
 11  babies                          7323 non-null   float64
 12  meal                            7323 non-null   object
 13  country                         7320 non-null   object
 14  market_segment                  7323 non-null   object
 15  distribution_channel            7323 non-null   object
 16  is_repeated_guest               7323 non-null   float64
 17  previous_cancellations          7323 non-null   float64
 18  previous_bookings_not_canceled  7323 non-null   float64
 19  reserved_room_type              7323 non-null   object
 20  assigned_room_type              7323 non-null   object
 21  booking_changes                 7323 non-null   float64
 22  deposit_type                    7323 non-null   object
 23  agent                           6167 non-null   float64
 24  company                         405 non-null    float64
 25  days_in_waiting_list            7323 non-null   float64
 26  customer_type                   7323 non-null   object
 27  adr                             7323 non-null   float64
 28  required_car_parking_spaces     7323 non-null   float64
 29  total_of_special_requests       7323 non-null   float64
 30  reservation_status              7323 non-null   object
 31  reservation_status_date         7323 non-null   object
dtypes: float64(17), int64(3), object(12)
memory usage: 1.8+ MB

===== STATISTICAL SUMMARY =====

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
count,7324,7324.000000,7324.000000,7324.000000,7324,7323.000000,7323.000000,7323.000000,7323.000000,7323.000000,...,7323,6167.000000,405.000000,7323.000000,7323,7323.000000,7323.000000,7323.000000,7323,7323
unique,1,NaN,NaN,NaN,13,NaN,NaN,NaN,NaN,NaN,...,3,NaN,NaN,NaN,4,NaN,NaN,NaN,3,473
top,Resort Hotel,NaN,NaN,NaN,July,NaN,NaN,NaN,NaN,NaN,...,No Deposit,NaN,NaN,NaN,Transient,NaN,NaN,NaN,Canceled,2016-01-05
freq,7324,NaN,NaN,NaN,1347,NaN,NaN,NaN,NaN,NaN,...,6507,NaN,NaN,NaN,5351,NaN,NaN,NaN,3867,74
mean,NaN,0.544238,99.665620,2015.489623,NaN,28.785334,15.963813,1.265328,3.377031,1.952205,...,NaN,215.289282,232.637037,1.404479,NaN,90.993664,0.070736,0.546770,NaN,NaN
std,NaN,0.498073,81.012128,0.499926,NaN,12.519150,9.010036,1.156521,2.445361,1.310937,...,NaN,79.445398,82.178110,11.833602,NaN,50.408462,0.257994,0.797833,NaN,NaN
min,NaN,0.000000,0.000000,2015.000000,NaN,1.000000,1.000000,0.000000,0.000000,0.000000,...,NaN,2.000000,12.000000,0.000000,NaN,0.000000,0.000000,0.000000,NaN,NaN
25%,NaN,0.000000,34.000000,2015.000000,NaN,19.000000,8.000000,0.000000,2.000000,2.000000,...,NaN,240.000000,223.000000,0.000000,NaN,55.000000,0.000000,0.000000,NaN,NaN
50%,NaN,1.000000,80.000000,2015.000000,NaN,29.000000,16.000000,1.000000,3.000000,2.000000,...,NaN,240.000000,223.000000,0.000000,NaN,79.330000,0.000000,0.000000,NaN,NaN
75%,NaN,1.000000,154.000000,2016.000000,NaN,39.000000,24.000000,2.000000,5.000000,2.000000,...,NaN,242.000000,281.000000,0.000000,NaN,118.245000,0.000000,1.000000,NaN,NaN
max,NaN,1.000000,737.000000,2016.000000,NaN,53.000000,31.000000,13.000000,33.000000,55.000000,...,NaN,405.000000,416.000000,122.000000,NaN,332.000000,2.000000,4.000000,NaN,NaN

Dataset Shape:
(7324, 32)

Columns:
Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type', 'agent',
       'company', 'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date'],
      dtype='object')

===== MISSING VALUES =====
hotel                                0
is_canceled                          0
lead_time                            0
arrival_date_year                    0
arrival_date_month                   0
arrival_date_week_number             1
arrival_date_day_of_month            1
stays_in_weekend_nights              1
stays_in_week_nights                 1
adults                               1
children                             1
babies                               1
meal                                 1
country                              4
market_segment                       1
distribution_channel                 1
is_repeated_guest                    1
previous_cancellations               1
previous_bookings_not_canceled       1
reserved_room_type                   1
assigned_room_type                   1
booking_changes                      1
deposit_type                         1
agent                             1157
company                           6919
days_in_waiting_list                 1
customer_type                        1
adr                                  1
required_car_parking_spaces          1
total_of_special_requests            1
reservation_status                   1
reservation_status_date              1
dtype: int64

CSV file exported successfully!
Excel file exported successfully!
Dataset exported successfully to SQLite database!

In [ ]:
import pandas as pd

# Load dataset, skipping bad lines to avoid ParserError
df = pd.read_csv("/content/sample_data/hotel_bookings.csv", on_bad_lines='skip', engine='python')

print("===== DATASET INFO ====")
df.info()

print("\n===== MISSING VALUES IN EACH COLUMN ====")
print(df.isnull().sum())

print("\n===== TOTAL MISSING VALUES ====")
print(df.isnull().sum().sum())

print("\n===== ANY MISSING VALUES? ====")
print(df.isnull().values.any())

print("\n===== NON-MISSING VALUES COUNT ====")
print(df.notnull().sum())

===== DATASET INFO ====
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97261 entries, 0 to 97260
Data columns (total 32 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   hotel                           97261 non-null  object
 1   is_canceled                     97261 non-null  int64
 2   lead_time                       97261 non-null  int64
 3   arrival_date_year               97261 non-null  int64
 4   arrival_date_month              97261 non-null  object
 5   arrival_date_week_number        97261 non-null  int64
 6   arrival_date_day_of_month       97261 non-null  int64
 7   stays_in_weekend_nights         97261 non-null  object
 8   stays_in_week_nights            97261 non-null  object
 9   adults                          97260 non-null  float64
 10  children                        97260 non-null  object
 11  babies                          97260 non-null  float64
 12  meal                            97260 non-null  object
 13  country                         96789 non-null  object
 14  market_segment                  97260 non-null  object
 15  distribution_channel            97260 non-null  object
 16  is_repeated_guest               97259 non-null  float64
 17  previous_cancellations          97259 non-null  float64
 18  previous_bookings_not_canceled  97259 non-null  float64
 19  reserved_room_type              97259 non-null  object
 20  assigned_room_type              97259 non-null  object
 21  booking_changes                 97259 non-null  float64
 22  deposit_type                    97259 non-null  object
 23  agent                           83741 non-null  float64
 24  company                         5788 non-null   float64
 25  days_in_waiting_list            97259 non-null  object
 26  customer_type                   97259 non-null  object
 27  adr                             97258 non-null  float64
 28  required_car_parking_spaces     97258 non-null  float64
 29  total_of_special_requests       97258 non-null  object
 30  reservation_status              97258 non-null  object
 31  reservation_status_date         97257 non-null  object
dtypes: float64(10), int64(5), object(17)
memory usage: 23.7+ MB

===== MISSING VALUES IN EACH COLUMN ====
hotel                                 0
is_canceled                           0
lead_time                             0
arrival_date_year                     0
arrival_date_month                    0
arrival_date_week_number              0
arrival_date_day_of_month             0
stays_in_weekend_nights               0
stays_in_week_nights                  0
adults                                1
children                              1
babies                                1
meal                                  1
country                             472
market_segment                        1
distribution_channel                  1
is_repeated_guest                     2
previous_cancellations                2
previous_bookings_not_canceled        2
reserved_room_type                    2
assigned_room_type                    2
booking_changes                       2
deposit_type                          2
agent                             13520
company                           91473
days_in_waiting_list                  2
customer_type                         2
adr                                   3
required_car_parking_spaces           3
total_of_special_requests             3
reservation_status                    3
reservation_status_date               4
dtype: int64

===== TOTAL MISSING VALUES ====
105505

===== ANY MISSING VALUES? ====
True

===== NON-MISSING VALUES COUNT ====
hotel                             97261
is_canceled                       97261
lead_time                         97261
arrival_date_year                 97261
arrival_date_month                97261
arrival_date_week_number          97261
arrival_date_day_of_month         97261
stays_in_weekend_nights           97261
stays_in_week_nights              97261
adults                            97260
children                          97260
babies                            97260
meal                              97260
country                           96789
market_segment                    97260
distribution_channel              97260
is_repeated_guest                 97259
previous_cancellations            97259
previous_bookings_not_canceled    97259
reserved_room_type                97259
assigned_room_type                97259
booking_changes                   97259
deposit_type                      97259
agent                             83741
company                            5788
days_in_waiting_list              97259
customer_type                     97259
adr                               97258
required_car_parking_spaces       97258
total_of_special_requests         97258
reservation_status                97258
reservation_status_date           97257
dtype: int64

In [ ]:

# Ensure 'children' column is numeric, coercing errors to NaN
df['children'] = pd.to_numeric(df['children'], errors='coerce')

# Fill all missing values with 0
df_constant = df.fillna(0)
print("===== CONSTANT VALUE ====")
display(df_constant.head())

# Fill 'children' column with mean
df_mean = df.copy()
df_mean["children"] = df_mean["children"].fillna(df_mean["children"].mean())
print("\n===== MEAN ====")
display(df_mean.head())

# Fill 'children' column with median
df_median = df.copy()
df_median["children"] = df_median["children"].fillna(df_median["children"].median())
print("\n===== MEDIAN ====")
display(df_median.head())

# Fill 'country' column with mode
df_mode = df.copy()
df_mode["country"] = df_mode["country"].fillna(df_mode["country"].mode()[0])
print("\n===== MODE ====")
display(df_mode.head())

# Forward Fill
df_ffill = df.ffill()
print("\n===== FORWARD FILL ====")
display(df_ffill.head())

# Backward Fill
df_bfill = df.bfill()
print("\n===== BACKWARD FILL ====")
display(df_bfill.head())

===== CONSTANT VALUE ====

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2.0,...,No Deposit,0.0,0.0,0,Transient,0.0,0.0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2.0,...,No Deposit,0.0,0.0,0,Transient,0.0,0.0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1.0,...,No Deposit,0.0,0.0,0,Transient,75.0,0.0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1.0,...,No Deposit,304.0,0.0,0,Transient,75.0,0.0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2.0,...,No Deposit,240.0,0.0,0,Transient,98.0,0.0,1,Check-Out,2015-07-03

===== MEAN ====

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2.0,...,No Deposit,NaN,NaN,0,Transient,0.0,0.0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2.0,...,No Deposit,NaN,NaN,0,Transient,0.0,0.0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1.0,...,No Deposit,NaN,NaN,0,Transient,75.0,0.0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1.0,...,No Deposit,304.0,NaN,0,Transient,75.0,0.0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2.0,...,No Deposit,240.0,NaN,0,Transient,98.0,0.0,1,Check-Out,2015-07-03

===== MEDIAN ====

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2.0,...,No Deposit,NaN,NaN,0,Transient,0.0,0.0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2.0,...,No Deposit,NaN,NaN,0,Transient,0.0,0.0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1.0,...,No Deposit,NaN,NaN,0,Transient,75.0,0.0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1.0,...,No Deposit,304.0,NaN,0,Transient,75.0,0.0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2.0,...,No Deposit,240.0,NaN,0,Transient,98.0,0.0,1,Check-Out,2015-07-03

===== MODE ====

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2.0,...,No Deposit,NaN,NaN,0,Transient,0.0,0.0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2.0,...,No Deposit,NaN,NaN,0,Transient,0.0,0.0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1.0,...,No Deposit,NaN,NaN,0,Transient,75.0,0.0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1.0,...,No Deposit,304.0,NaN,0,Transient,75.0,0.0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2.0,...,No Deposit,240.0,NaN,0,Transient,98.0,0.0,1,Check-Out,2015-07-03

===== FORWARD FILL ====

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2.0,...,No Deposit,NaN,NaN,0,Transient,0.0,0.0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2.0,...,No Deposit,NaN,NaN,0,Transient,0.0,0.0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1.0,...,No Deposit,NaN,NaN,0,Transient,75.0,0.0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1.0,...,No Deposit,304.0,NaN,0,Transient,75.0,0.0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2.0,...,No Deposit,240.0,NaN,0,Transient,98.0,0.0,1,Check-Out,2015-07-03

===== BACKWARD FILL ====

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2.0,...,No Deposit,304.0,110.0,0,Transient,0.0,0.0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2.0,...,No Deposit,304.0,110.0,0,Transient,0.0,0.0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1.0,...,No Deposit,304.0,110.0,0,Transient,75.0,0.0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1.0,...,No Deposit,304.0,110.0,0,Transient,75.0,0.0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2.0,...,No Deposit,240.0,110.0,0,Transient,98.0,0.0,1,Check-Out,2015-07-03